print('Birthday Calculator')
print('Current Day')
current_month=int(input("Enter current Month number:"))
current_day=int(input("Enter current Day:"))
current_year=int(input("Enter current Year:"))
print('Birthday')
birth_month=int(input("Enter birth month number:"))
birth_day=int(input("Enter birthday day number:"))
birth_year=int(input("Enter birth year number:"))
age=(current_year-birth_year-1)
print('You are', age, 'years old.')
if(current_month == birth_month and current_day == birth_day): print("Happy Birthday!")